#!/bin/sh

echo "Compile"

mkdir -p target/classes target/test-classes

javac -d target/classes -classpath "lib/servlet-api.jar;target/classes" src/main/java/com/baldurtech/*.java

javac -d target/test-classes -classpath "lib-test/reflections-0.9.9-RC2.jar;target/classes;target/test-classes" src/test/java/com/baldurtech/unit/*.java

javac -encoding "UTF-8" -d target/test-classes -classpath "lib-test/reflections-0.9.9-RC2.jar;target/classes;target/test-classes" src/test/java/com/baldurtech/*.java

CLASSPATH="target/classes;target/test-classes"

echo "Compile done"
