#!/bin/sh

APPNAME=addressbook
rm -r -f $CATALINA_HOME/webapps/$APPNAME

cp -r src/main/webapp $CATALINA_HOME/webapps/$APPNAME
cp -r target/classes $CATALINA_HOME/webapps/$APPNAME/WEB-INF/

echo "Deploy done."
