#!/bin/sh

echo "Run test"

CLASSPATH_TEST="lib-test/reflections-0.9.9-RC2.jar;target/test-classes;target/classes"
CLASSPATH_TEST="$CLASSPATH_TEST;lib-test/guava-15.0.jar"
CLASSPATH_TEST="$CLASSPATH_TEST;lib-test/javassist-3.18.2-GA.jar"

java -classpath "$CLASSPATH_TEST" com.baldurtech.unit.MiniatureSpiceTestCase "com.baldurtech"
RETVAL=$?

echo "Test done."
exit $RETVAL
